codecov:
  require_ci_to_pass: true
coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      api-unit:
        target: 80%
        threshold: 1%
        branches:
          - main
        if_ci_failed: error
        only_pulls: false
        flags:
          - api-unit
        paths:
          - api/
      web-unit:
        target: 80%
        threshold: 1%
        branches:
          - main
        if_ci_failed: error
        only_pulls: false
        flags:
          - web-unit
        paths:
          - web/
      infra-unit:
        target: 80%
        threshold: 1%
        branches:
          - main
        if_ci_failed: error
        only_pulls: false
        flags:
          - infra-unit
        paths:
          - infra/
    patch: off

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: 80%
        threshold: 1%
  individual_flags:
    - name: api-unit
      paths:
        - api/
      carryforward: true
    - name: web-unit
      paths:
        - web/
      carryforward: true
    - name: infra-unit
      paths:
        - infra/
      carryforward: true