codecov:
  require_ci_to_pass: true
coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        branches:
          - main
          - github-actions-setup
        if_ci_failed: error
        only_pulls: false
        flags:
          - api-unit
          - web-unit
          - infra-unit
        paths:
          - api/
          - web/
          - infra/

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: 80%
        threshold: 1%
      - type: patch
        target: 85%
  individual_flags:
    - name: api
      paths:
      - api/
      carryforward: true
    - name: web
      paths:
      - web/
      carryforward: true
    - name: infra
      paths:
      - infra/
      carryforward: true