coverage:
  status:
    project: off
    patch: off

flag_management:
  individual_flags:
    - name: api-unit
      paths:
        - api/
      statuses:
        - type: project
          target: 80%
          threshold: 1%
    - name: web-unit
      paths:
        - web/
      statuses:
        - type: project
          target: 80%
          threshold: 1%
    - name: infra-unit
      paths:
        - infra/
      statuses:
        - type: project
          target: 80%
          threshold: 1%