import { ColorSchemeScript } from '@mantine/core';
import '@mantine/core/styles.css';
import { Amplify } from 'aws-amplify';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';
import amplifyConfig from '../config/amplifyConfig';
import './globals.css';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

Amplify.configure(amplifyConfig);

const RootLayout = ({ children }: PropsWithChildren) => {
    return (
        <html lang='en'>
            <head>
                <ColorSchemeScript />
            </head>
            <body className={`${inter.className} h-full w-full`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
};

export default RootLayout;
