AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.github.giessc.inctrl::inctrl-api
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  InctrlApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.github.giessc.inctrl.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  InctrlApiApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: InctrlApiApi
