name: Tests and Code Coverage
on:
  push:
    branches:
      - $default-branch
      - github-actions-setup
  pull_request:
    branches:
      - $default-branch
jobs:
  web-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./web/node_modules
      - name: Install Dependencies
        run: npm install
        working-directory: ./web
      - name: Run Tests
        run: npm test -- --coverage --passWithNoTests
        working-directory: ./web
  infrastructure-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./infra/node_modules
      - name: Install Dependencies
        run: npm install
        working-directory: ./infra
      - name: Run Tests
        run: npm test -- --coverage --passWithNoTests
        working-directory: ./infra
  api-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
      - uses: nuget/setup-nuget@v2
      - uses: actions/cache@v4
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: nuget restore InControl.sln
        working-directory: ./api
      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ./api
      - name: Run Tests
        run: dotnet test
        working-directory: ./api

