name: Code Coverage and Tests

on:
  push:
    branches:
      - $default-branch
      - github-actions-setup
  pull_request:
    branches:
      - $default-branch

jobs:
  api-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Navigate to API folder
      run: cd api/src/InControl.Api/

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.101'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Run .NET tests
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      continue-on-error: true

    # - name: Publish .NET Test Results
      # run:

  web-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Navigate to Web
      run: cd web/

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test -- --coverage
      continue-on-error: true

  infrastructure-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Navigate to Infra
      run: cd infra/

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.0.0'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test -- --coverage
      continue-on-error: true
